In [60]:
import pandas as pd
import numpy as np
import re


class DataLoader(object):
    def fit(self, dataset):
        self.dataset = dataset.copy()

    # apply regex
    def get_title(self, name):
        pattern = ' ([A-Za-z]+)\.'
        title_search = re.search(pattern, name)
        # If the title exists, extract and return it.
        if title_search:
            return title_search.group(1)
        return ""

    def load_data(self):
        
        #outliers
#         df = self.dataset.drop("FALLING",axis=1)
#         Q1 = self.dataset.quantile(0.25)
#         Q3 = self.dataset.quantile(0.75)
#         IQR = Q3 - Q1
#         self.dataset = self.dataset[~((self.dataset.loc[:, self.dataset.columns != 'FALLING'] < (Q1 - 1.5 * IQR)) |
#                                       (self.dataset.loc[:, self.dataset.columns != 'FALLING'] > (Q3 + 1.5 * IQR))).any(axis=1)]
        
        #drop columns
        self.dataset = self.dataset.drop(['SL','EEG'], axis=1)

        return self.dataset

In [61]:
dl = DataLoader()

In [62]:
db = pd.read_csv('data/train.csv')
db_test = pd.read_csv('data/val.csv')

In [63]:
dl.fit(db)
df = dl.load_data()
dl.fit(db_test)
df_test = dl.load_data()
df_test[:10]

TIME   BP   HR  CIRCULATION  FALLING
0   9582.21   92  136          619        1
1   5717.83   24  102          764        0
2  11899.00   25  223         1809        0
3  20476.40  358  517        11883        0
4   7463.33   35  131          271        0
5   4649.90   28   71          249        1
6  12181.70   21  249         3630        0
7   4704.48   34   71          249        1
8   4258.17    5   63          166        1
9   3954.47   42   52          133        0

In [64]:
X_train, y_train = df.drop(['FALLING'], axis=1), df['FALLING']
X_test, y_test = df_test.drop(['FALLING'], axis=1), df_test['FALLING']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=50)

In [65]:
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression

In [66]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_predict = lr.predict(X_test)

# Print confusion matrix and accuracy score
lr_conf_matrix = confusion_matrix(y_test, lr_predict)
lr_acc_score = accuracy_score(y_test, lr_predict)
lr_class_report = classification_report(y_test, lr_predict) 
print(lr_conf_matrix)
print('Accuracy Score :', '%.2f' %lr_acc_score)
print('Classification Report :')
print(lr_class_report)

[[1885    1]
 [ 572    0]]
Accuracy Score : 0.77
Classification Report :
              precision    recall  f1-score   support

           0       0.77      1.00      0.87      1886
           1       0.00      0.00      0.00       572

    accuracy                           0.77      2458
   macro avg       0.38      0.50      0.43      2458
weighted avg       0.59      0.77      0.67      2458



In [67]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
dt_predict = dt.predict(X_test)

# Print confusion matrix and accuracy score
dt_conf_matrix = confusion_matrix(y_test, dt_predict)
dt_acc_score = accuracy_score(y_test, dt_predict)
dt_class_report = classification_report(y_test, dt_predict) 
print(dt_conf_matrix)
print('Accuracy Score :', '%.2f' %dt_acc_score)
print('Classification Report :')
print(dt_class_report)

[[1641  245]
 [ 240  332]]
Accuracy Score : 0.80
Classification Report :
              precision    recall  f1-score   support

           0       0.87      0.87      0.87      1886
           1       0.58      0.58      0.58       572

    accuracy                           0.80      2458
   macro avg       0.72      0.73      0.72      2458
weighted avg       0.80      0.80      0.80      2458



In [68]:
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)
knn_predict = knn.predict(X_test)

# Print confusion matrix and accuracy score
knn_conf_matrix = confusion_matrix(y_test, knn_predict)
knn_acc_score = accuracy_score(y_test, knn_predict)
knn_class_report = classification_report(y_test, knn_predict) 
print(knn_conf_matrix)
print('Accuracy Score :', '%.2f' %knn_acc_score)
print('Classification Report :')
print(knn_class_report)

[[1688  198]
 [ 274  298]]
Accuracy Score : 0.81
Classification Report :
              precision    recall  f1-score   support

           0       0.86      0.90      0.88      1886
           1       0.60      0.52      0.56       572

    accuracy                           0.81      2458
   macro avg       0.73      0.71      0.72      2458
weighted avg       0.80      0.81      0.80      2458



In [70]:
nb = GaussianNB()
nb.fit(X_train,y_train)
nb_predict = nb.predict(X_test)

# Print confusion matrix and accuracy score
nb_conf_matrix = confusion_matrix(y_test, nb_predict)
nb_acc_score = accuracy_score(y_test, nb_predict)
nb_class_report = classification_report(y_test, nb_predict) 
print(nb_conf_matrix)
print('Accuracy Score :', '%.2f' %nb_acc_score)
print('Classification Report :')
print(nb_class_report)

[[1886    0]
 [ 572    0]]
Accuracy Score : 0.77
Classification Report :
              precision    recall  f1-score   support

           0       0.77      1.00      0.87      1886
           1       0.00      0.00      0.00       572

    accuracy                           0.77      2458
   macro avg       0.38      0.50      0.43      2458
weighted avg       0.59      0.77      0.67      2458



c:\users\my_ro\app\venv\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\my_ro\app\venv\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\my_ro\app\venv\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [71]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf_predict = rf.predict(X_test)

# Print confusion matrix and accuracy score
rf_conf_matrix = confusion_matrix(y_test, rf_predict)
rf_acc_score = accuracy_score(y_test, rf_predict)
rf_class_report = classification_report(y_test, rf_predict)
print(rf_conf_matrix)
print('Accuracy Score :','%.2f' %rf_acc_score)
print('Classification Report :')
print(rf_class_report)

[[1739  147]
 [ 231  341]]
Accuracy Score : 0.85
Classification Report :
              precision    recall  f1-score   support

           0       0.88      0.92      0.90      1886
           1       0.70      0.60      0.64       572

    accuracy                           0.85      2458
   macro avg       0.79      0.76      0.77      2458
weighted avg       0.84      0.85      0.84      2458



In [72]:
svc = SVC()
svc.fit(X_train,y_train)
svc_predict = svc.predict(X_test)

# Print confusion matrix and accuracy score
svc_conf_matrix = confusion_matrix(y_test, svc_predict)
svc_acc_score = accuracy_score(y_test, svc_predict)
svc_class_report = classification_report(y_test, svc_predict)
print(svc_conf_matrix)
print('Accuracy Score :','%.2f' %svc_acc_score)
print('Classification Report :')
print(svc_class_report)

[[1886    0]
 [ 572    0]]
Accuracy Score : 0.77
Classification Report :
              precision    recall  f1-score   support

           0       0.77      1.00      0.87      1886
           1       0.00      0.00      0.00       572

    accuracy                           0.77      2458
   macro avg       0.38      0.50      0.43      2458
weighted avg       0.59      0.77      0.67      2458



c:\users\my_ro\app\venv\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\my_ro\app\venv\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\my_ro\app\venv\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [73]:
import pickle
import json
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

from utils.dataloader import DataLoader 
from settings.constants import TRAIN_CSV


with open('settings/specifications.json') as f:
    specifications = json.load(f)

raw_train = pd.read_csv(TRAIN_CSV)
# x_columns = specifications['description']['X']
# y_column = specifications['description']['y']

# x_raw = raw_train[x_columns]

loader = DataLoader()
loader.fit(raw_train)
new = loader.load_data()
X = new.drop('FALLING',axis = 1)
y = new.FALLING


model = RandomForestClassifier()
model.fit(X, y)
with open('models/RFC.pickle', 'wb')as f:
    pickle.dump(model, f)